spring:
  cloud:
    kubernetes:
      discovery:
        catalogServicesWatchDelay: 5000
        service-labels:
          type: spring-boot

  boot:
    admin:
      monitor:
        status-interval: 3s
        status-lifetime: 3s
      context-path: "/sbaadmin"

server:
  servlet:
    context-path: "/admin"
  port: 8080