server:
  servlet:
    context-path: "/orderservice"
  port: 8081
spring:
  application:
    name: orderservice

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: "/"
    port: 9080