apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sbaadmin
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sbaadmin
  namespace: shopping
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sbaadmin
subjects:
  - kind: ServiceAccount
    name: sbaadmin
    namespace: shopping
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbaadmin