apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sbaadmin
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sbaadmin
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sbaadmin
subjects:
  - kind: ServiceAccount
    name: sbaadmin
    namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbaadmin
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: sbaadmin-service
  labels:
    type: spring-boot
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: sbaadmin